run:
  timeout: 5m
  modules-download-mode: readonly
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gosec
    - misspell
    - revive
    - stylecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/sand/crypto-trading-app

issues:
  exclude-dirs:
    - frontend
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false
