services:
  crypto-trading-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: crypto-trading-app
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/api/pairs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
